apiVersion: v1
kind: Service
metadata:
  name: hpa-demo-app
  labels:
    app: hpa-demo-app
    namespace: default
spec:
  selector:
    app: hpa-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
